name: Project Assignment
run-name: Runcomparison triggered by ${{ github.triggering_actor }}
on:
  issue_comment:
    types: [created, edited]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  check-comment:
    if: (github.event.issue.pull_request != null) && contains(github.event.comment.body, '/wandb')
    runs-on: ubuntu-latest
    steps:        

    - name: Get repo contents
      uses: actions/checkout@v4

    - name: Install dependencies
      run: pip install ghapi wandb

    - name: Parse value from the command
      id: get-runid-value
      shell: python
      run: |
        import re, os
        comment = os.getenv('PR_COMMENT', '')
        match = re.search('/wandb[\s+](\S+)', comment)

        with open(os.environ['GITHUB_OUTPUT'], 'a') as f:
          if match:
            print(f'VAL_FOUND=true', file=f)
            print(f'RUN_ID={match.group(1)}', file=f)
          else:
            print(f'VAL_FOUND=false', file=f)
      env:
        PR_COMMENT: ${{ github.event.comment.body }}

    - name: Generate the comparison report
      if: steps.get-runid-value.outputs.VAL_FOUND == 'true'
      id: wandb-report
      run: python ./client/compare_runs.py
      env:
        WANDB_ENTITY: arrogantemartin
        WANDB_PROJECT: cicd-quickstart
        BASELINE_TAG: baseline
        RUN_ID: "${{ steps.get-runid-value.outputs.RUN_ID }}"
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}

    - name: Make a comment with the GitHub API
      if: steps.wandb-report.outcome == 'success' 
      run: python ./client/make_comment.py
      env:
        REPORT_URL: "${{ steps.wandb-report.outputs.REPORT_URL }}"
        PR_NUMBER: "${{ github.event.issue.number }}"
        GITHUB_TOKEN: ${{ github.token }}