on: push

jobs:
  secrets:
    runs-on: ubuntu-latest
    steps:
      - shell: python
        run: |
          import os
          print(os.getenv('MY_SECRET'))
        env:
          MY_SECRET: ${{ secrets.DUMMY_SECRET }}
